image:
  repository: "quay.io/iris"
  tag: "latest"
pullPolicy: "alwaysPull"
replicaCount: 1

service:
  externalPort: 80
  internalPort: 8080
  dbInitialized: False
  auth:
    debug: True
    module: debug
    # config:
    #   ldap_url: 'ldaps://example.com'
    #   ldap_user_suffix: '@example.biz'
    #   ldap_cert_path: '/etc/ldap_cert.pem'
    #   ldap_bind_user: 'cn=binduser,ou=services,dc=company,dc=org'
    #   ldap_bind_password: 'abc123'
    #   ldap_base_dn: 'ou=accounts,dc=company,dc=org'
    #   ldap_search_filter: '(uid=%s)'
    #   import_user: True
    #   attrs:
    #     username: 'uid'
    #     full_name: 'displayName'
    #     email: 'mail'
    #     mobile: 'mobile'
    #     sms: 'phone'
    #     slack: 'uid'
  timezone: 'US/Pacific'

ingress:
  enabled: False
  class: nginx
  certManager: True
  hostname: "test.com"
  tls: True

mysql:
  auth:
    rootPassword: "1234"
  primary:
    persistence:
      size: 1Gi
