image:
  repository: "quay.io/iris"
  tag: "latest"
pullPolicy: "alwaysPull"
replicaCount: 1

oncallService:
  externalPort: 80
  internalPort: 8080
  dbInitialized: false

mysql:
  auth:
    rootPassword: "1234"
