apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "fullname" . }}
  labels:
    oncall-component: api
    oncall-component: web
    oncall-component: sender
    oncall-version: {{ .Chart.AppVersion }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    app: {{ template "fullname" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ template "fullname" . }}
  template:
    metadata:
      labels:
        app: {{ template "fullname" . }}
    spec:
      containers:
        - name: oncall
          image: {{ .Values.imageRegistry }}/oncall:{{.Values.dockerTag}}
          imagePullPolicy: {{ default "" .Values.imagePullPolicy | quote }}
          ports:
            - containerPort: {{ .Values.oncallService.internalPort }}
          env:
            - name: DOCKER_DB_BOOTSTRAP
              value: '1'
            - name: oncall_CFG_DB_USER
              value: root
            - name: oncall_CFG_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ template "mysql.fullname" . }}
                  key: mysql-root-password
            - name: oncall_CFG_DB_HOST
              value: {{ template "mysql.fullname" . }}
          volumeMounts:
            - name: oncall-volume
              mountPath: /home/oncall/config
              readOnly: true
      volumes:
        - name: oncall-volume
          configMap:
            name: oncall-config
