apiVersion: v1
kind: Service
metadata:
  name: {{ template "name" . }}
  labels:
    oncall-component: api
    oncall-component: web
    oncall-version: {{ .Chart.AppVersion }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
spec:
  ports:
    - name: {{ template "name" . }}
      port: {{ .Values.service.externalPort }}
      targetPort: {{ .Values.service.internalPort }}
      protocol: TCP
  selector:
    app: {{ template "fullname" . }}
  type: NodePort
